-- migration_v7.sql
-- Amaç: faqs tablosuna 4 TEKNOFEST 2026 yarışması için sıkça sorulan soru-cevap
-- kayıtlarının eklenmesi.
--
-- Kapsam: her yarışma için 10 kayıt olmak üzere toplam 40 satır eklenir.
--   * 5g_yz_yol     : 5G & Yapay Zeka ile Akıllı Yol Güvenliği Yarışması
--   * biyoteknoloji : Biyoteknoloji İnovasyon Yarışması
--   * blokzincir    : Blokzincir Yarışması
--   * cip_tasarim   : Çip (Tümdevre) Tasarım Yarışması
--
-- Sorular yarışmacıların doğal diliyle Türkçe olarak yazılmıştır. Tüm cevaplar
-- ilgili yarışmanın 2026 şartnamesi (ve 5G yarışması için FTR Aşaması Teslim
-- Dokümanı) metninden birebir doğrulanmış bilgilere dayanır ve her cevap
-- kaynak madde numarası ile (Madde X.Y) biçiminde sonlandırılmıştır.
--
-- Not: source_ticket_id alanı NULL bırakılmıştır; bu kayıtlar destek talebinden
-- değil doğrudan şartname metninden üretilmiştir.


-- 5g_yz_yol (10 kayıt)
INSERT INTO faqs (competition_id, question, answer) VALUES
  ('5g_yz_yol', 'Bu yarışmanın amacı tam olarak nedir?', 'Yarışma, 5G şebekesinin yeteneklerini API''ler aracılığıyla kullanarak yapay zekâ modellerinden yararlanan, katma değerli çözüm üreten uygulamalar geliştirilmesini hedefliyor. Takımlar canlı video akışını yapay zekâ temelli algoritmayla işleyerek faydalı veri çıkarımı yapacak. (Madde 1)'),
  ('5g_yz_yol', 'Takım kaç kişiden oluşabilir, kimler katılabilir?', 'Yarışmaya Türkiye ve yurt dışında öğrenim gören lisans, yüksek lisans, doktora ve açık öğretim öğrencileri takım halinde katılabilir. Takımlar en az 2, en fazla 5 kişiden oluşmalı ve bu kişilerden biri İletişim Sorumlusu olarak görevlendirilmelidir; danışman bu sayıya dahil değildir. (Madde 3)'),
  ('5g_yz_yol', 'Son başvuru tarihi ne zaman ve başvuru nereden yapılıyor?', 'Yarışma son başvuru tarihi 28 Şubat 2026''dır ve başvurular TEKNOFEST resmi web sitesi (www.TEKNOFEST.org) üzerinden takımlar şeklinde yapılır. (Madde 6.1)'),
  ('5g_yz_yol', 'Rapor teslim tarihleri neler?', 'Ön Tasarım Raporunun son teslim tarihi 24.04.2026 saat 17:00, Final Tasarım Raporunun son teslim tarihi ise 14.06.2026 saat 17:00''dir. Ön tasarım raporu sonuçları 01.06.2026''da, final yarışmaya katılacak takımlar 31.07.2026''da açıklanır. (Madde 6)'),
  ('5g_yz_yol', 'Final puanlaması hangi kriterlere göre yapılıyor?', 'Yapay zekâ analizinin (araç, plaka, gerçek hız, araç içi nesne tanıma) doğruluk ve hassasiyeti %40, 5G ağ API''leriyle uygulama entegrasyonu %40, final tasarım raporu ve sunumu %20 ağırlığındadır. (Madde 5)'),
  ('5g_yz_yol', 'Ödül tutarları ne kadar?', 'Birincilik ödülü 175.000 TL, ikincilik 150.000 TL, üçüncülük 125.000 TL''dir; danışman ödülleri sırasıyla 15.000 TL, 12.000 TL ve 10.000 TL''dir. Ödüller takıma verilen toplam tutar olup üye sayısına (danışman hariç) eşit bölünerek ödenir. (Madde 7)'),
  ('5g_yz_yol', 'Hangi 5G API''lerini kullanmamız gerekiyor?', 'Turkcell tarafından sağlanacak Numara Doğrulama (Number Verification) ve Talep Üzerine Kalite (Quality on Demand) API''leri kullanılacaktır. Uygulamaya kullanıcı girişi Number Verification ile doğrulanmalı, aracın yakınlığına göre daha yüksek çözünürlüklü video akışı Quality on Demand API''si ile talep edilmelidir. (Madde 2)'),
  ('5g_yz_yol', 'Final günü yarışma alanında takımdan kaç kişi bulunabilir?', 'Final yarışması sırasında yarışma alanında her takımdan en fazla 3 yarışmacı bulunabilir; 3''ten fazla yarışmacısı olan takımlar farklı oturumlarda dönüşümlü olarak alanda bulunabilir. Ulaşım ve konaklama desteği de takım başına en fazla 3 kişi (danışman dahil) içindir. (Madde 3)'),
  ('5g_yz_yol', 'Değerlendirme sunucusunun donanımı ve süre sınırı nedir?', 'Projeler izole bir Docker konteyneri olarak 4 vCPU, 16 GB RAM, NVIDIA Tesla T4 GPU ve 2 GB paylaşımlı bellek bulunan sunucuda test edilir; temel imaj nvidia/cuda:12.1.0-base-ubuntu22.04, imaj boyutu en fazla 8 GB ve maksimum çalışma süresi 10 dakikadır. Dockerfile build süresi bu süreye dahil edilmez. (FTR Aşaması Teslim Dokümanı, Madde 6)'),
  ('5g_yz_yol', 'Model çıktısını hangi formatta ve nereye kaydetmeliyiz?', 'Çıktılar results.json adıyla /app/data/output/results.json yoluna kaydedilmeli; girdi videosu ise /app/data/input/video.mp4 yolundan okunmalıdır. Tüm etiketler Türkçe karakter içermeyen (ASCII) ve küçük harf olmalı, JSON anahtarları örneklerdeki isimlerle birebir aynı kullanılmalıdır. (FTR Aşaması Teslim Dokümanı, Madde 4)');

-- biyoteknoloji (10 kayıt)
INSERT INTO faqs (competition_id, question, answer) VALUES
  ('biyoteknoloji', 'Yarışmanın kategorileri neler?', 'Yarışma üç kategoride yapılır: Lise Kategorisi (fikir ve proje ayrımı yoktur), Üniversite Seviyesi Fikir Kategorisi ve Üniversite Seviyesi Proje Kategorisi. Başvurular Tablo 1''de listelenen sekiz ana çalışma alanı kapsamında yapılır. (Madde 2)'),
  ('biyoteknoloji', 'Yarışma ne amaçla düzenleniyor?', 'Yarışma; inovasyon ve yüksek teknoloji alanlarındaki çalışmalara özendirmek, biyoteknolojinin farklı alanlarında farkındalık oluşturmak ve bu alandaki inovatif fikirleri desteklemek amacıyla düzenlenmektedir. (Madde 3)'),
  ('biyoteknoloji', 'Kimler başvurabilir, yaş sınırı var mı?', 'Yarışmaya Türkiye''de ve yurt dışında öğrenim gören, T.C. vatandaşı veya yabancı uyruklu, 14-30 yaş arası tüm lise, ön lisans, lisans ve yüksek lisans öğrencileri katılabilir. Başvuru yapılan tarihteki eğitim seviyesi esas alınır ve kategori bu seviyeye uygun seçilmelidir. (Madde 4.2)'),
  ('biyoteknoloji', 'Lise kategorisinde takım kaç kişi olabilir, danışman zorunlu mu?', 'Lise Kategorisinde takımlar en fazla 6 öğrenciden oluşabilir ve bu sayıya danışman dahil değildir; bu kategoride danışman bulundurmak zorunludur. Lise mezunları, mezuniyetlerinden en fazla üç yıl geçmişse Lise Kategorisine başvurabilir. (Madde 4.3)'),
  ('biyoteknoloji', 'Fikir ve Proje kategorileri için THS seviyesi kaç olmalı?', 'Üniversite Seviyesi Fikir Kategorisinde THS 1-2 seviyesindeki projeler kabul edilir, THS 3 ve üzeri projeler teknik kontrolde elenir. Üniversite Seviyesi Proje Kategorisinde ise THS 4 ve üzeri projeler kabul edilir, THS 4''ün altındakiler elenir. (Madde 4.5)'),
  ('biyoteknoloji', 'Hangi durumlarda projem ön elemede elenir?', 'Takım yapısının şartları sağlamaması, yarışma kapsamı dışında konu seçilmesi, THS seviyesinin beyan edilmemesi, daha önce başka yarışmaya katılmış projede esaslı değişiklik yapılmaması, Fikir kategorisine patent almış veya THS 3 ve üzeri makale yayımlanmış projeyle başvurulması ve kurallara uymayan THS seviyesiyle katılım ön eleme sebeplerindendir. (Madde 5)'),
  ('biyoteknoloji', 'Rapor teslim tarihleri ne zaman?', 'Proje Ön Değerlendirme Raporunun (ÖDR) son teslim tarihi 09.04.2026 saat 17:00, Proje Detay Raporunun (PDR) son teslim tarihi 29.06.2026 saat 17:00''dir. Ön elemeyi geçen takımlar 11.05.2026''da, PDR sonuçları ile finale kalan takımlar 31.07.2026''da açıklanır. (Madde 7.1)'),
  ('biyoteknoloji', 'Toplam puan nasıl dağılıyor?', 'Proje Detay Raporu toplam puanın %20''sini, Final Sunum ve Prototip puanlaması ise %80''ini oluşturur. (Madde 7.2)'),
  ('biyoteknoloji', 'Rapor sonucuna nasıl itiraz edebilirim?', 'Takımların baraj puanının en fazla 25 puan altında kalması durumunda itiraz hakkı bulunur. İtirazlar, sonuçların açıklanmasından sonraki 48 saat içinde KYS üzerinden, takım danışmanı veya takım kaptanı tarafından yapılmalıdır; süresinde iletilmeyen itirazlar değerlendirilmez. (Madde 8.3)'),
  ('biyoteknoloji', 'Ödül tutarları kategorilere göre ne kadar?', 'Lise Kategorisinde birincilik 90.000 TL, ikincilik 80.000 TL, üçüncülük 70.000 TL; Üniversite Seviyesi Fikir Kategorisinde 120.000 TL, 100.000 TL ve 80.000 TL; Üniversite Seviyesi Proje Kategorisinde 180.000 TL, 150.000 TL ve 120.000 TL''dir. Danışman ödülü sırasıyla 15.000 TL, 12.000 TL ve 10.000 TL''dir. (Madde 9)');

-- blokzincir (10 kayıt)
INSERT INTO faqs (competition_id, question, answer) VALUES
  ('blokzincir', 'Yarışmanın amacı nedir?', 'TEKNOFEST Blokzincir Yarışması, blokzincir teknolojisine duyulan ilgiyi artırmak ve ülkemizdeki bilgi birikimi ile insan kaynağını geliştirmek amacıyla düzenlenmektedir. Yarışma, kamu yönetimi, eğitim, finans, bankacılık ve tedarik zinciri gibi alanlardaki gerçek dünya problemlerine blokzincir ile çözüm üretilmesini hedefler. (Madde 1)'),
  ('blokzincir', 'Projemin konusu serbest mi, kapsam dışı proje kabul ediliyor mu?', 'Kapsam; yüksek başarımlı ve ölçeklenebilir DLT altyapıları, DLT sistemlerinde mahremiyet, dijital cüzdanlar, blokzincir kriptolojisi, blokzincir güvenliği, kripto varlık regülasyon uygulama altyapıları ve seçilmiş DLT uygulama alanları başlıklarından oluşur. Bu ana başlıklar dışında hazırlanan projeler değerlendirmeye alınmayacaktır. (Madde 2)'),
  ('blokzincir', 'Kimler ve kaç kişilik takımlarla katılabilir?', 'Yarışmacılar en az 2 ve en fazla 5 kişilik takımlar (danışman hariç) halinde katılabilir. Her alandan ön lisans, lisans, yüksek lisans, doktora öğrencisi ve/veya mezuniyetinden sonra en fazla 3 yıl geçmiş mezun adaylar başvurabilir; yarışma uluslararası nitelikte olduğu için yabancı katılımcılara da açıktır. (Madde 3)'),
  ('blokzincir', 'Yarışma takvimi nasıl, hangi tarihte ne teslim ediliyor?', 'Son başvuru 28.02.2026; Proje Ön Değerlendirme Raporu 27.03.2026 saat 17.00, Proje Sunum Raporu 26.06.2026 saat 17.00, Özet Proje Sunum Raporu 10.07.2026 tarihinde teslim edilir. Çevrim içi proje sunumları 20-25.07.2026 arasında yapılır ve finalistler 31.07.2026''da açıklanır. (Madde 4)'),
  ('blokzincir', 'Puanlama yüzdeleri nasıl dağılıyor?', 'Proje Ön Değerlendirme Raporu %10, Proje Sunum Raporu %15, Özet Proje Sunum Puanlaması (çevrim içi) %15 ve Final Sunum Puanlaması %60 ağırlığındadır. (Madde 5)'),
  ('blokzincir', 'Projeler hangi kriterlere göre değerlendiriliyor?', 'Projeler katma değer ve yenilikçilik, teknoloji kullanımı, uygulanabilirlik, yaygın etki ve sürdürülebilirlik unsurları çerçevesinde değerlendirilir; proje mevcut bir probleme ya da ihtiyaca cevap verecek nitelikte olmalıdır. (Madde 6)'),
  ('blokzincir', 'Ön Değerlendirme Raporu için şablon var mı?', 'Evet, Ön Değerlendirme Rapor Şablonuna TEKNOFEST web sitesi üzerinden ulaşılabilir; raporlar bu şablona uygun hazırlanmalıdır. Rapor teslimi ile ilgili detaylı bilgilendirme başvuru tarihinin sona ermesinin ardından başvurusunu tamamlamış takımlarla paylaşılacaktır. (Madde 6.1)'),
  ('blokzincir', 'Rapor sonucuna itiraz süresi ne kadar?', 'Rapor itirazları, sonuçların açıklanmasından sonraki 48 saat içinde KYS üzerinden alınır ve takım danışmanı veya takım kaptanı tarafından yapılmalıdır. İtirazlar farklı hakem heyetlerine gönderilip yeniden değerlendirilir; itirazda da başarılı olamayan takımların iletisim@teknofest.org adresine dilekçe göndererek yüksek itiraz hakkı bulunmaktadır. (Madde 6.3)'),
  ('blokzincir', 'Çevrim içi sunum nasıl yapılıyor?', 'Proje Sunum aşamasına geçen takımlar sunumlarını takvimde belirtilen tarihte teslim eder; sunumu takvime ve kriterlere uygun teslim eden takımlar için çevrim içi sunum tarih ve saatleri belirlenir ve takım belirlenen saatte sunum yapmakla yükümlüdür. Çevrim içi sunum sonuçlarına göre finale katılacak takımlar açıklanır. (Madde 6.4)'),
  ('blokzincir', 'Ödüller ne kadar?', 'Birincilik 200.000 TL, ikincilik 150.000 TL, üçüncülük 100.000 TL''dir; danışman ödülleri sırasıyla 15.000 TL, 12.000 TL ve 10.000 TL''dir. Ödüller takım üyelerinin toplam sayısına eşit bölünerek her şahsın belirteceği banka hesabına yatırılır. (Madde 7)');

-- cip_tasarim (10 kayıt)
INSERT INTO faqs (competition_id, question, answer) VALUES
  ('cip_tasarim', 'Yarışmanın kategorileri neler ve her birinde ne bekleniyor?', 'Yarışma Analog Tasarım ve Mikrodenetleyici Tasarım olmak üzere iki kategoriden oluşur. TÜBİTAK''ın düzenlediği Analog kategoride SerDes analog ön-uç ve bant aralığı referans gerilim devrelerinin tasarımı, Yongatek''in düzenlediği Mikrodenetleyici kategoride ise hazır verilen bir işlemci çekirdeği ile arayüz ve bellek birimlerine sahip bir mikrodenetleyicinin tasarımı ve doğrulaması beklenir. (Madde 3)'),
  ('cip_tasarim', 'Rapor teslim tarihleri ne zaman?', 'Ön Tasarım Raporu (ÖTR) son teslim tarihi 16.03.2026 saat 17.00, Detay Tasarım Raporu (DTR) son teslim tarihi 07.06.2026 saat 23.59''dur. Ön elemeyi geçen takımlar 12.04.2026''da, finalist takımlar 26.06.2026''da açıklanır ve tasarımın nihai hale getirilmesi 31.07.2026 saat 17.00''dir. (Madde 2)'),
  ('cip_tasarim', 'Takım kaç kişi olabilir, yüksek lisans öğrencisi sınırı var mı?', 'Yarışmaya bireysel veya takım olarak katılınabilir; takımlar en fazla 5 kişiden oluşmalıdır (danışman hariç) ve takımdaki yüksek lisans öğrencisi sayısı 2''yi geçmemelidir. Takımlar yalnızca 1 kişiyi danışman olarak alabilir, danışman almak şart değildir. (Madde 3.1)'),
  ('cip_tasarim', 'Raporların sayfa ve format kuralları nedir?', 'Raporlar son teslim tarihlerinde saat 17.00''ye kadar, en fazla 60 MB büyüklüğünde ve PDF formatında yüklenir; aksi halde takım elenir. A4 formatında, 11 punto, Calibri fontunda, 1.15 satır aralığı ve 2.5 cm kenar boşluklarıyla hazırlanmalı; Ön Tasarım Raporu en fazla 9, Detay Tasarım Raporu en fazla 30 sayfa olmalıdır (kapak, resim, tablo ve referanslar dahil). (Madde 3.2)'),
  ('cip_tasarim', 'GitHub deposunu ne sıklıkla güncellemeliyiz?', 'Mikrodenetleyici Tasarım kategorisinde tasarım, değerlendirme kurulu ile paylaşılan özel bir GitHub deposunda en seyrek 20 günlük periyotlarla güncellenmelidir ve depo Mikrodenetleyici kategorisi için yongatek-teknofest hesabıyla paylaşılmalıdır. Analog kategoride açık erişim EDA aracı kullanılırsa DTR ve final sunumu öncesi GitHub deposu güncellenmeli, ticari EDA aracı kullanılırsa depoya ihtiyaç yoktur. (Madde 4.1)'),
  ('cip_tasarim', 'Analog kategoride toplam puan nasıl hesaplanıyor?', 'Puanlama 100 üzerindendir ve Toplam Puan = (0.15 x ÖTR Puanı) + (0.25 x DTR Puanı) + (0.35 x Sunum) + (0.25 x Başarım Kriterleri Puanı) şeklinde hesaplanır. Başarım kriterleri puanı alıcı ön-uç devresi sonrası göz açıklığı, toplam alan ve güç tüketimi dikkate alınarak belirlenir. (Madde 3.3.1)'),
  ('cip_tasarim', 'Mikrodenetleyici kategorisinde puan dağılımı nasıl?', 'Toplam Puan = (0.1 x ÖTR Puanı) + (0.15 x DTR Puanı) + (0.05 x Sunum Puanı) + (0.1 x Demo Puanı) + (0.4 x Tasarım ve Doğrulama Puanı) + (0.2 x Çip Akışı Puanı) olarak hesaplanır ve maksimum 100 puandır. (Madde 3.3.2)'),
  ('cip_tasarim', 'Bant aralığı referans devresi için isterler neler?', 'Devre 1.25 V referans gerilimi üretmeli; referans gerilimi -40 C ila 125 C aralığında en fazla 15 ppm/C değişim göstermeli ve devre 16 uA referans akımına sahip olmalıdır. 1.8 V besleme geriliminin %10 değişiminde 1.25 V referans değişmemeli, açılış problemleri için start-up devresi kurulmalı ve PSRR 1 Hz-10 GHz aralığında 0 dB''nin altında olmalıdır. (Madde 4.2.1.3)'),
  ('cip_tasarim', 'Mikrodenetleyicide hangi çekirdek ve çevre birimleri olacak?', 'OpenHW Group tarafından sürdürülen, tek çekirdekli, 32-bit 4 aşamalı boru hattına sahip açık kaynaklı CV32E40P RISC-V çekirdek IP kullanılacaktır. Mikrodenetleyicide 1x GPIO (32 pin I/O), 1x Timer, 2x UART (biri genel kullanım, biri YZ veri akışı için), 1x I2C Master, 1x QSPI Master ve opsiyonel 1x JTAG bulunacak; çekirdek 8 kB buyruk ve 8 kB veri belleği içerecek, YZ hızlandırıcı ise 30 kB bellek barındıracaktır. (Madde 4.2.2.1)'),
  ('cip_tasarim', 'Ödül tutarları ne kadar?', 'Her iki kategoride de birincilik 200.000 TL, ikincilik 175.000 TL, üçüncülük 150.000 TL''dir; danışman ödülleri sırasıyla 20.000 TL, 15.000 TL ve 12.000 TL''dir. Kategoriler ayrı ayrı değerlendirilip ödüllendirilir ve ödüller takım üyeleri sayısına eşit bölünerek ödenir. (Madde 5)');
